### 1. How to concatenate two numpy arrays column-wise and row-wise?

In [1]:
import numpy as np
import pandas as pd

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [2]:
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 2. Consider the random number generation functions in NumPy generate a set of random numbers using the function rand.

In [3]:
from numpy import random

x = random.rand(5)
print(x)

[0.67267881 0.06743131 0.20126267 0.65130458 0.83075187]


### 3. Create a 3D array of shape 5x3x2 to contain random decimal numbers between 5 and 10.

In [4]:
arr_3d = np.random.randint(5, 10, size=(5, 3, 2))
print(arr_3d)

[[[5 5]
  [8 8]
  [8 5]]

 [[7 8]
  [5 5]
  [5 8]]

 [[5 9]
  [5 6]
  [9 5]]

 [[9 6]
  [7 9]
  [6 8]]

 [[5 6]
  [6 6]
  [5 6]]]


### 4. Create a utility function to generate random arrays using def random_array() takes number of elements as one of the argument, and randint() from random library. 
    * Note: Do not use numpy function in this


In [5]:
import random
def random_array(n):
    x=random.sample(range(1,50),n)
    print(x)
    
random_array(random.randint(1,10))

[1]


### 5. Create and Compute median using both Naive method using python only and Numpy function np.median()

In [6]:
#using numpy
arr = [20, 2, 7, 1, 34]
#print("arr : ", arr) 
print("median of arr : ", np.median(arr))

#using python
import statistics
print("median of arr : %s" %(statistics.median(arr)))

median of arr :  7.0
median of arr : 7


### 6. Create naive function to compute variance function, mean function using only python.

In [7]:
sample = [2.74, 1.23, 2.63, 2.22, 3, 1.98]
print("Mean of sample set is %s" %(statistics.mean(sample)))
print("Variance of sample set is %s" %(statistics.variance(sample)))

Mean of sample set is 2.3
Variance of sample set is 0.40924


### 7. Convert a 1D array to a 2D array with 2 rows.

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)

print('2D Numpy array:')
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D Numpy array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


### 8. How to stack two arrays vertically? Stack arrays A and B vertically?

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

### 9. Create a function using numpy to get the common items between two python numpy arrays?

In [10]:
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = np.array([1, 3, 4, 5, 8])
  
print(np.intersect1d(ar1, ar2))

[1 3 4]


### 10. Create a python function to get the positions where elements of two arrays match using Numpy function?

In [11]:
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = np.array([1, 3, 4, 5, 8])
  
print(np.where(np.intersect1d(ar1, ar2)))

(array([0, 1, 2], dtype=int64),)


### 11. How to create a 2D array containing random floats between 5 and 10?

In [12]:
random_float_array = np.random.uniform(5,10,size=(2,2))
print(random_float_array)

[[6.89585325 5.75142129]
 [8.93284281 7.97198459]]


### 12. Extract the text column species from the 1D iris imported using following url np.genfromtxt()
https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv


In [13]:
import pandas as pd


iris_df = pd.read_csv("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv")
iris_df


sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [27]:
iris_dataset=np.genfromtxt("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv")
iris_dataset

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan])

### 14. How to compute the mean, median, standard deviation of a numpy array on the same iris dataset?

In [16]:
iris_df.agg(['mean','median','std'])

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.057333      3.758000     1.199333
median      5.800000     3.000000      4.350000     1.300000
std         0.828066     0.435866      1.765298     0.762238

### 15. How to scale an array so the values range exactly between 0 and 1 using Admission.csv?
https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Admission.csv
### Change all the values in the range of 0-1.


In [17]:
admission_df = pd.read_csv("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Admission.csv")
admission_df



Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [18]:
def NormalizeData(data):
    return (data - np.min(data)) / (np.max(data) - np.min(data))
scaled = NormalizeData(admission_df)
print(scaled)

     Serial No.  GRE Score  TOEFL Score  University Rating    SOP   LOR   \
0      0.000000       0.94     0.928571               0.75  0.875  0.875   
1      0.002004       0.68     0.535714               0.75  0.750  0.875   
2      0.004008       0.52     0.428571               0.50  0.500  0.625   
3      0.006012       0.64     0.642857               0.50  0.625  0.375   
4      0.008016       0.48     0.392857               0.25  0.250  0.500   
..          ...        ...          ...                ...    ...    ...   
495    0.991984       0.84     0.571429               1.00  0.875  0.750   
496    0.993988       0.94     0.892857               1.00  1.000  1.000   
497    0.995992       0.80     1.000000               1.00  0.875  1.000   
498    0.997996       0.44     0.392857               0.75  0.750  1.000   
499    1.000000       0.74     0.750000               0.75  0.875  0.875   

         CGPA  Research  Chance of Admit   
0    0.913462       1.0          0.920635  

### 16. Compute and Find the number and position of missing values in iris data’s sepal length column.
### (And few missing values).


In [19]:
iris_df['sepal_length'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
145    False
146    False
147    False
148    False
149    False
Name: sepal_length, Length: 150, dtype: bool

In [20]:
iris_df_temp = np.where(iris_df>5,np.nan,iris_df)
sepal_length_col = iris_df_temp[:,0]
print("position:\n{} \n count:{} ".format(np.argwhere(np.isnan(sepal_length_col)),len(np.argwhere(np.isnan(sepal_length_col)))

SyntaxError: unexpected EOF while parsing (<ipython-input-20-4260efad1e88>, line 3)

### 17. Drop rows that contain a missing value from a numpy array created by using iris dataset? 
    *Hint: There is no direct function for this hence, select the rows of Iris dataset that does not have any NaN value


In [21]:
iris_df_temp = np.where(iris_df>5,np.nan,iris_df)
iris_df_temp[~np.isnan(iris_df_temp).any(axis=1),:]

TypeError: '>' not supported between instances of 'str' and 'int'

### 18. Sort the Admission dataset array based on TOEFL Score column and GRE Score. Use separate code for both.

In [22]:
admission_df['TOEFL Score'].sort_values()

368     92
28      93
79      93
411     94
347     94
      ... 
81     120
97     120
297    120
143    120
497    120
Name: TOEFL Score, Length: 500, dtype: int64

In [23]:
admission_df['GRE Score'].sort_values()

377    290
117    290
168    293
79     294
272    294
      ... 
81     340
84     340
143    340
384    340
429    340
Name: GRE Score, Length: 500, dtype: int64

### 19. Compute the Euclidean distance between two arrays using Numpy linalg?

In [24]:
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))

dist = np.linalg.norm(point1 - point2)

print(dist)

2.23606797749979


### 20. Compute and Find the duplicate entries in the given Numpy array and mark them as True. Create 1-D array

In [25]:
arr = np.array([1,2,7,5,6,1,3,2,5])
def duplicates(arr):
    return [elem in arr[:i] for i, elem in enumerate(arr)]
res = duplicates(arr)
print(res)

[False, False, False, False, False, True, False, True, True]
